version: '3.7'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:${PORT:-8080}"
    environment:
      PORT: ${PORT:-8080}
    volumes:
      - .:/var/www/html